---
server:
  port: 9090

eureka:
  instance:
    hostname: ${HOSTNAME}
    instanceId: ${HOSTNAME}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:8761/eureka/